<?php

return [
	'default' => [
		'domain_id' => 1,
		'language_id' => 3,
		'product_family_id' => 1,
		//'account_id' => null,
		'currency_id' => 1,
		'unit_id' => 1,
	],
	'filters' => [
		'currency_id',
		'domain_id',
		'isLive',
		'isPublic',
		'isStream',
		'quantity'
	],
	'items' => [
		1 => [
			'internal_id' => 1,
			'title' => 'Regular review - public - pre-recorded',
			'description' => 'Regular review',
			'isLive' => 0,
			'isPublic' => 1,
			'isStream' => 0,
			'quantity' => '15.00',
			'price' => '30.00',
		],
		2 => [
			'internal_id' => 2,
			'title' => 'Long review - public - pre-recorded',
			'description' => 'Long review',
			'isLive' => 0,
			'isPublic' => 1,
			'isStream' => 0,
			'quantity' => '30.00',
			'price' => '60.00',
		],
		3 => [
			'internal_id' => 3,
			'title' => 'Regular review - private - pre-recorded',
			'description' => 'Regular review',
			'isLive' => 0,
			'isPublic' => 0,
			'isStream' => 0,
			'quantity' => '15.00',
			'price' => '35.00',
		],
		4 => [
			'internal_id' => 4,
			'title' => 'Long review - private - pre-recorded',
			'description' => 'Long review',
			'isLive' => 0,
			'isPublic' => 0,
			'isStream' => 0,
			'quantity' => '30.00',
			'price' => '70.00',
		],
		5 => [
			'internal_id' => 5,
			'title' => 'Regular review - public - live',
			'description' => 'Regular review',
			'isLive' => 1,
			'isPublic' => 1,
			'isStream' => 0,
			'quantity' => '15.00',
			'price' => '40.00',
		],
		6 => [
			'internal_id' => 6,
			'title' => 'Long review - public - live',
			'description' => 'Long review',
			'isLive' => 1,
			'isPublic' => 1,
			'isStream' => 0,
			'quantity' => '30.00',
			'price' => '80.00',
		],
		7 => [
			'internal_id' => 7,
			'title' => 'Regular review - private - live',
			'description' => 'Regular review',
			'isLive' => 1,
			'isPublic' => 0,
			'isStream' => 0,
			'quantity' => '15.00',
			'price' => '45.00',
		],
		8 => [
			'internal_id' => 8,
			'title' => 'Long review - private - live',
			'description' => 'Long review',
			'isLive' => 1,
			'isPublic' => 0,
			'isStream' => 0,
			'quantity' => '30.00',
			'price' => '90.00',
		],
		9 => [
			'internal_id' => 9,
			'title' => 'Regular review - public - stream',
			'description' => 'Regular review',
			'isLive' => 0,
			'isPublic' => 1,
			'isStream' => 1,
			'quantity' => '15.00',
			'price' => '50.00',
		],
		10 => [
			'internal_id' => 10,
			'title' => 'Long review - public - stream',
			'description' => 'Long review',
			'isLive' => 0,
			'isPublic' => 1,
			'isStream' => 1,
			'quantity' => '30.00',
			'price' => '55.00',
		]
	]
];
